name: Run Comparison Script
on:
  pull_request_target:
    branches: [ "main" ]
    types: [opened]
  
jobs:     
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Comparison Action
        uses: oxygenxml/oxygen-script-comparison-action@v1.0.0
        env:
          SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
        with:
          firstBranch: main
          secondBranch: ${{ github.event.pull_request.head.sha }}
